---

- import_playbook: config_initial/main.yml
- import_playbook: docker/main.yml
- import_playbook: suricata/main.yml
- import_playbook: clamav/main.yml
- import_playbook: openvas/main.yml

- import_playbook: auditd/main.yml


# reference:
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/import_playbook_module.html