---
##
## DEFAULT METHOD - ROLES BELOW HERE 
##

#initial tasks:
- name: "{{ cluster }} - {{ cluster_process }}"
  hosts: "{{ ansible_pull_hosts }}"
  tags: [tags]
  become: yes
  vars_files:
    - template_ansible_pull_variables.yml
  
  ##
  ## PREP TASKS
  ##

  pre_tasks:
    #create directory
    - name: Play-00a Create Reports Directory
      ignore_errors: yes
      shell: |
        mkdir /home/{{ user }}/ansible/reports && \
        chmod 600 /home/{{ user }}/ansible/reports && \
        chown {{ user }} /home/emh/ansible/reports && \
        chgrp {{ user }} /home/emh/ansible/reports

    #copy template report file
    - name: Play-00b Copy Template Playbook Report
      ansible.builtin.copy:
        src: "/home/{{ user }}/ansible/{{ role_process }}/files/template_report.json"
        dest: /home/{{ user }}/ansible/reports/{{ role_process }}_install.json
        owner: root
        group: root
        mode: '600'
    
    #editing entries for the report title block
    - name: "Play-00c Edit Report Title Block"
      shell: |
        sed -i "s/^\"title\":*/\"title\": \"{{ role }} - {{ role_process }}\"/" /home/{{ user }}/ansible/reports/{{ role_process }}_install.json && \
        sed -i "s/^\"date_time\":*/\"date_time\": \"{{ now(utc=true,fmt='%Y-%m-%d %H:%M:%S') }}\"/" /home/{{ user }}/ansible/reports/{{ role_process }}.json && \
        sed -i "s/^\"gen_by\":*/\"gen_by\": \"Ansible\"/" /home/{{ user }}/ansible/reports/{{ role_process }}.json && \
        sed -i "s/^\"operator\":*/\"operator\": \"Ansible\"/" /home/{{ user }}/ansible/reports/{{ role_process }}.json && \
        sed -i "s/^\"total_entries\":*/\"total_entries\": {{ role_plays }}/" /home/{{ user }}/ansible/reports/{{ role_process }}.json
    
    ##
    ## ADDITIONAL PREP TASKS (IF ANY)
    ##

    #pre_task 1
    - name: [name]
      tags: [tags]
      ansible.builtin.include_tasks: "{{ playbook01 }}.yml"
      #when: ansible_distribution == "Ubuntu"
      #when: ansible_distribution in ["Ubuntu", "Debian"]

    #pre_task 2
    - name: [name]
      tags: [tags]
      ansible.builtin.include_tasks: "{{ playbook02 }}.yml"
    
    #pre_task 3
    - name: [name]
      tags: [tags]
      ansible.builtin.include_tasks: "{{ playbook03 }}.yml"

#role-group 1
- name: [name]
  hosts: [hosts]
  tags: [tags]
  become: yes
  roles:
    - {{ role01 }}
    - {{ role02 }}
    - {{ role03 }}
    - {{ role04 }}
    - {{ role05 }}

#role-group 2
- name: [name]
  hosts: [hosts]
  tags: [tags]
  become: yes
  roles:
    - {{ role06 }}
    - {{ role07 }}
    - {{ role08 }}
    - {{ role09 }}
    - {{ role10 }}


##
## ALTERNATIVE METHOD WITH REGISTERS - ROLES BELOW HERE
##

- name: "{{ cluster }} - {{ cluster_process }}"
  hosts: "{{ ansible_pull_hosts }}"
  gather_facts: no
  become: yes
  vars_files:
    - template_ansible_pull_variables.yml
  tasks:

    - name: Role 01
      ansible.builtin.include_role:
          name: package_manager_bootstrap
          tasks_from: apt.yml
      #when: ansible_facts['os_family'] == 'Debian
      register: role01_status
    
    - name: Role 01
      ansible.builtin.include_role:
          name: package_manager_bootstrap
          tasks_from: apt.yml
      #when: ansible_facts['os_family'] == 'Debian
      register: role02_status
    
    - name: Role 01
      ansible.builtin.include_role:
          name: package_manager_bootstrap
          tasks_from: apt.yml
      #when: ansible_facts['os_family'] == 'Debian
      register: role03_status
    
    - name: Role 01
      ansible.builtin.include_role:
          name: package_manager_bootstrap
          tasks_from: apt.yml
      #when: ansible_facts['os_family'] == 'Debian
      register: role04_status


    ##
    ## REPORT DATA ENTRY BELOW HERE
    ##

    #add entries
    - name: Play-100-01 Generate Playbook Report Task-01
      shell: |
        sed -i "s/^\"ent_01_int_value\":*/\"ent_01_int_value\": \" {{ play_01_status.rc }}\"/" /home/{{ user }}/ansible/reports/{{cluster_process}}.json && \
        sed -i "s/^\"ent_01_str_value\":*/\"ent_01_str_value\": \" {{ play_01_status.stdout }}\"/" /home/{{ user }}/ansible/reports/{{cluster_process}}.json
    
    #add entries
    - name: Play-100-02 Generate Playbook Report Task-02
      shell: |
        sed -i "s/^\"ent_02_int_value\":*/\"ent_02_int_value\": \" {{ play_02_status.rc }}\"/" /home/{{ user }}/ansible/reports/{{cluster_process}}.json && \
        sed -i "s/^\"ent_02_str_value\":*/\"ent_02_str_value\": \" {{ play_02_status.stdout }}\"/" /home/{{ user }}/ansible/reports/{{cluster_process}}.json
    
    #add entries
    - name: Play-100-03 Generate Playbook Report Task-03
      shell: |
        sed -i "s/^\"ent_03_int_value\":*/\"ent_03_int_value\": \" {{ play_03_status.rc }}\"/" /home/{{ user }}/ansible/reports/{{cluster_process}}.json && \
        sed -i "s/^\"ent_03_str_value\":*/\"ent_03_str_value\": \" {{ play_03_status.stdout }}\"/" /home/{{ user }}/ansible/reports/{{cluster_process}}.json
    
    #add entries
    - name: Play-100-04 Generate Playbook Report Task-04
      shell: |
        sed -i "s/^\"ent_04_int_value\":*/\"ent_04_int_value\": \" {{ play_04_status.rc }}\"/" /home/{{ user }}/ansible/reports/{{cluster_process}}.json && \
        sed -i "s/^\"ent_04_str_value\":*/\"ent_04_str_value\": \" {{ play_04_status.stdout }}\"/" /home/{{ user }}/ansible/reports/{{cluster_process}}.json
    
    #add entries
    - name: Play-100-05 Generate Playbook Report Task-05
      shell: |
        sed -i "s/^\"ent_05_int_value\":*/\"ent_05_int_value\": \" {{ play_05_status.rc }}\"/" /home/{{ user }}/ansible/reports/{{cluster_process}}.json && \
        sed -i "s/^\"ent_05_str_value\":*/\"ent_05_str_value\": \" {{ play_05_status.stdout }}\"/" /home/{{ user }}/ansible/reports/{{cluster_process}}.json

    #add entries
    - name: Play-100-06 Generate Playbook Report Task-06
      shell: |
        sed -i "s/^\"ent_06_int_value\":*/\"ent_06_int_value\": \" {{ play_06_status.rc }}\"/" /home/{{ user }}/ansible/reports/{{cluster_process}}.json && \
        sed -i "s/^\"ent_06_str_value\":*/\"ent_06_str_value\": \" {{ play_06_status.stdout }}\"/" /home/{{ user }}/ansible/reports/{{cluster_process}}.json
    
    #add entries
    - name: Play-100-07 Generate Playbook Report Task-07
      shell: |
        sed -i "s/^\"ent_07_int_value\":*/\"ent_07_int_value\": \" {{ play_07_status.rc }}\"/" /home/{{ user }}/ansible/reports/{{cluster_process}}.json && \
        sed -i "s/^\"ent_07_str_value\":*/\"ent_07_str_value\": \" {{ play_07_status.stdout }}\"/" /home/{{ user }}/ansible/reports/{{cluster_process}}.json
    
    #add entries
    - name: Play-100-08 Generate Playbook Report Task-08
      shell: |
        sed -i "s/^\"ent_08_int_value\":*/\"ent_08_int_value\": \" {{ play_08_status.rc }}\"/" /home/{{ user }}/ansible/reports/{{cluster_process}}.json && \
        sed -i "s/^\"ent_08_str_value\":*/\"ent_08_str_value\": \" {{ play_08_status.stdout }}\"/" /home/{{ user }}/ansible/reports/{{cluster_process}}.json
    
    #add entries
    - name: Play-100-09 Generate Playbook Report Task-09
      shell: |
        sed -i "s/^\"ent_09_int_value\":*/\"ent_09_int_value\": \" {{ play_09_status.rc }}\"/" /home/{{ user }}/ansible/reports/{{cluster_process}}.json && \
        sed -i "s/^\"ent_09_str_value\":*/\"ent_09_str_value\": \" {{ play_09_status.stdout }}\"/" /home/{{ user }}/ansible/reports/{{cluster_process}}.json
    
    #add entries
    - name: Play-100-10 Generate Playbook Report Task-10
      shell: |
        sed -i "s/^\"ent_10_int_value\":*/\"ent_10_int_value\": \" {{ play_10_status.rc }}\"/" /home/{{ user }}/ansible/reports/{{cluster_process}}.json && \
        sed -i "s/^\"ent_10_str_value\":*/\"ent_10_str_value\": \" {{ play_10_status.stdout }}\"/" /home/{{ user }}/ansible/reports/{{cluster_process}}.json
